# This is for an OS other than Fedora 18

- name: Install missing packages required for KA Lite startup
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-virtualenv

- name: Download KA Lite's requirements file
  get_url:
    url: "{{ kalite_requirements }}"
    dest: "{{ pip_packages_dir }}/kalite.txt"
    timeout: "{{ download_timeout }}"
  when: internet_available

#- name: Install KA Lite non-static + reqs file with pip - (debuntu)
#  pip: requirements={{ pip_packages_dir }}/kalite.txt
#       virtualenv={{ kalite_venv }}
#       virtualenv_site_packages=no
#       extra_args="--no-cache-dir"
#       extra_args="--disable-pip-version-check"
#  when: internet_available and is_debuntu

- name: Install KA Lite static with pip (debuntu)
  pip:
    name: ka-lite-static
    version: "{{ kalite_version }}"
    virtualenv: "{{ kalite_venv }}"
    virtualenv_site_packages: no
    extra_args: "--no-cache-dir"
#       extra_args="--disable-pip-version-check"
  when: internet_available and is_debuntu

#- name: Install KA Lite non-static + reqs file with pip (OS's other than debuntu)
#  pip: requirements={{ pip_packages_dir }}/kalite.txt
#       virtualenv={{ kalite_venv }}
#       virtualenv_site_packages=no
#       extra_args="--no-cache-dir"
#       extra_args="--disable-pip-version-check"
#  when: internet_available and not is_debuntu

- name: Install KA Lite static with pip (OS's other than debuntu)
  pip:
    name: ka-lite-static
    version: "{{ kalite_version }}"
    virtualenv: "{{ kalite_venv }}"
    virtualenv_site_packages: no
#       extra_args="--no-cache-dir"
#       extra_args="--disable-pip-version-check"
  when: internet_available and not is_debuntu

# This effectively does nothing at all on Ubuntu & Raspbian, where libgeos-*
# pkgs are not installed FWIW.  But it's included to safeguard us across all
# OS's, in case others OS's like Ubermix later appear.  See #1382 for details.
# Removing pkgs libgeos-3.6.2 & libgeos-c1v5 fixed the situation on Ubermix!
- name: Remove libgeos-* pkgs, avoiding KA Lite Django failure on Ubermix
  shell: apt -y remove "libgeos-*"

- name: Default is to have cronserve started with KA Lite
  set_fact:
    job_scheduler_stanza: ""

- name: Add --skip-job-scheduler to start if cronserve not enabled
  set_fact:
    job_scheduler_stanza: "--skip-job-scheduler "
  when: not kalite_cron_enabled

- name: Create 'kalite-serve' service, kalite.sh and kalite.conf
  template:
    backup: no
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'kalite-serve.service.j2', dest: '/etc/systemd/system/kalite-serve.service', mode: '0644'}
    - { src: 'kalite.sh.j2', dest: '/usr/bin/kalite', mode: '0755'}
    - { src: 'kalite.conf', dest: '/etc/{{ apache_config_dir }}', mode: '0644'}
