- hosts: all
  become: yes

  vars_files:
  - vars/default_vars.yml
  - vars/{{ ansible_local.local_facts.os_ver }}.yml
  - /etc/iiab/local_vars.yml

  roles:
    - { role: 0-init, tags: ['0-init'] }
    #- { role: 1-prep, tags: ['1-prep', 'platform', 'base'] }
    - { role: 1-prep, tags: ['1-prep'] }
    #- { role: openvpn, tags: ['openvpn'] }    # FASTER ALTERNATIVE THAN 1-prep (if 1-prep was already run!)
    # BETTER YET, SEE: /usr/bin/iiab-support for a much friendlier UX, that only runs 1-prep when necessary.
