- name: Fail if nodejs_version is incorrect
  fail:
    msg: >-
      PBX: Refusing to install as nodejs_version is not 10.x.  Please fix that
      (looking into /etc/iiab/local_vars.yml and
      /opt/iiab/iiab/vars/default_vars.yml) and then rerun.
  when: pbx_install and (nodejs_version != "10.x")

#- name: TODO: Check if asterisk and freepbx are already installed

- debug:    # Crazy spacing below is tuned for 80-column screens
    msg: >-
      ####################################################################WARNING:
      ONLY UBUNTU 18.04 AND DEBIAN 9 ARE SUPPORTED AS OF FEBRUARY 2019.      Please
      assist Internet-in-a-Box communities worldwide if you can make
      Asterisk  and FreePBX work on other OS's / distros, Thank
      You!  http://FAQ.IIAB.IO        ###############################################################################

- name: Install Asterisk (debuntu)
  include_tasks: asterisk.yml
  when: internet_available and pbx_install and (not pbx_installed) and is_debuntu
  #when: internet_available and pbx_install and (not pbx_installed) and ((is_debian and ansible_distribution_major_version == "9") or is_ubuntu_18)

- name: Install FreePBX (debuntu)
  include_tasks: freepbx.yml
  when: internet_available and pbx_install and (not pbx_installed) and is_debuntu
  #when: internet_available and pbx_install and (not pbx_installed) and ((is_debian and ansible_distribution_major_version == "9") or is_ubuntu_18)
