# Use these to tag a release at a point in time, for {{ iiab_env_file }}
iiab_base_ver: 7.0
iiab_revision: 0

# These entries should never be changed in this file.
# These are defaults for boolean routines.
first_run: False
rpi_model: none
is_rpi: False
xo_model: none
gw_active: none
internet_available: False
discovered_wan_iface: none

# Old defs
gui_port: 80
exFAT_enabled: False
is_F18: False

# Set default 1-prep discovered hardware
rtc_id: ds3231
NUC6_firmware_needed: False

# Used in 2-common/tasks/xo.yml
wifi_id: none

# Used in 2-common, 3-base-server and roles/network
installing: False

# Network
no_net_restart: False
no_NM_reload: False
