# https://remote.it can help you remotely maintain an IIAB.

# remoteit_install: True
# remoteit_enabled: False

# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!

# See https://docs.remote.it/cli/overview to refine either value below:
remoteit_version: 4.13.5
iset_suffixes:
  x86_64: amd64
  aarch64: arm64
  armv8: arm64.rpi
  armv6: armhf.rpi
  armv6l: armhf.rpi
  armv7: armhf.rpi
  armv7l: armhf.rpi
remoteit_iset_suffix: "{{ iset_suffixes[ansible_architecture] | default('unknown') }}"
remoteit_deb: remoteit-{{ remoteit_version }}.{{ remoteit_iset_suffix }}.deb
remoteit_device_url: https://downloads.remote.it/remoteit/v{{ remoteit_version }}/{{ remoteit_deb }}

iset_suffixes2:
  x86_64: amd64
  aarch64: arm64
  armv6: armv6
  armv6l: armv6
  armv7: armv7
  armv7l: armv7
  armv8: arm64
remoteit_iset_suffix2: "{{ iset_suffixes2[ansible_architecture] | default('unknown') }}"
remoteit_cli_url: https://downloads.remote.it/cli/latest/remoteit_linux_{{ remoteit_iset_suffix2 }}
