# A full-featured online radio station suite.
# Works on Ubuntu 18.04, Debian 9, 10. Uses docker

# azuracast_install: False
# azuracast_enabled: False

# azuracast_http_port: 10080
# azuracast_https_port: 10443

## AzuraCast needs many ports in the 8000:8100 range by default, but IIAB services
## conflict with those ports so this variable below sets a sane prefix. 
## e.g. setting the below variable to 10 will result in port ranges 10000-10100 
## being reserved for AzuraCast:
# azuracast_port_range_prefix: 10

# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!

docker_sh_url: https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker.sh
docker_compose_url: https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker-compose.sample.yml 
docker_container_dir: /library/docker
azuracast_host_dir: /opt/azuracast
