# SEE "emergency" REINSTALL INSTRUCTIONS IN roles/wordpress/tasks/install.yml

- name: Install WordPress if wordpress_installed is absent
  include_tasks: install.yml
  when: wordpress_install and not wordpress_installed is defined

- name: Provision MySQL DB for WordPress
  include_tasks: setup.yml
  when: wordpress_install and not installing

- name: Enable WordPress
  include_tasks: enable.yml
  when: wordpress_install or wordpress_installed is defined
