# XO Services

- name: ...IS BEGINNING =====================================
  command: echo

- name: ACTIVITY-SERVER
  import_role:
    name: activity-server
  when: activity_server_install
  tags: olpc, activity-server

- name: EJABBERD_XS
  import_role:
    name: ejabberd_xs
  when: ejabberd_xs_install
  tags: olpc, ejabberd-xs

- name: IDMGR
  import_role:
    name: idmgr
  when: idmgr_install
  tags: olpc, idmgr

- name: Recording STAGE 5 HAS COMPLETED =====================
  lineinfile:
    dest: /etc/iiab/iiab.env
    regexp: '^STAGE=*'
    line: 'STAGE=5'
    state: present
