# nodered_install: False
# nodered_enabled: False
# nodered_port: 1880

# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!

nodered_web_path: nodered    # http://box/nodered redirect to http://box:1880

nodered_user: Admin
nodered_password: changeme
nodered_password_hash: $2b$08$oxgvoU9et3deSbXY8UNVTOWHSTQAyEASIal86RHVMqYQJhpPMNz7q
# To generate a new password hash, run 'node-red-admin hash-pw' and enter the
# new password.  Paste the resulting hash above.  After Ansible runs, username
# and password hash will be placed in: /home/nodered/.node-red/settings.js
