# Server Options

- name: ...IS BEGINNING ==================================
  command: echo

# MANDATORY SO PERHAPS THIS BELONGS IN 3-BASE-SERVER ?
- name: SSHD
  import_role:
    name: sshd
  # has no "when: XXXXX_install" flag
  tags: base, sshd

- name: OPENVPN
  import_role:
    name: openvpn
  when: openvpn_install
  tags: openvpn

#- name: Configuring wondershaper
#  include_tasks: roles/network/tasks/wondershaper.yml
#  when: wondershaper_install
#  tags: wondershaper, network

- name: Installing named
  include_tasks: roles/network/tasks/named.yml
  when: named_install
  tags: base, named, network, domain

- name: Installing dhcpd
  include_tasks: roles/network/tasks/dhcpd.yml
  when: dhcpd_install
  tags: base, dhcpd, network, domain

- name: Installing Squid
  include_tasks: roles/network/tasks/squid.yml
  when: squid_install
  tags: base, squid, network, domain

#- name: NETWORK
#  include_role:
#    name: network
#  # has no "when: XXXXX_install" flag
#  tags: base, network

# MANDATORY SO PERHAPS THIS BELONGS IN 3-BASE-SERVER ?
- name: HOMEPAGE
  import_role:
    name: homepage
  # has no "when: XXXXX_install" flag
  tags: base, homepage

- name: POSTGRESQL
  import_role:
    name: postgresql
  when: postgresql_install
  tags: postgresql, pathagar, moodle

- name: AUTHSERVER
  import_role:
    name: authserver
  when: authserver_install
  tags: olpc, authserver

- name: CUPS
  import_role:
    name: cups
  when: cups_install
  tags: cups

- name: SAMBA
  import_role:
    name: samba
  when: samba_install
  tags: samba

- name: USB-LIB
  import_role:
    name: usb-lib
  when: usb_lib_install
  tags: usb-lib

# MANDATORY SO PERHAPS THIS BELONGS IN 3-BASE-SERVER ?
- name: Create a Python interface to iiab.env
  template:
    src: roles/1-prep/templates/iiab_env.py.j2
    dest: /etc/iiab/iiab_env.py

- name: Generate the offline documents
  command: /usr/bin/iiab-refresh-wiki-docs
  when: not nodocs

- name: Recording STAGE 4 HAS COMPLETED ==================
  lineinfile:
    dest: /etc/iiab/iiab.env
    regexp: '^STAGE=*'
    line: 'STAGE=4'
    state: present
