# Server Options

- name: ...IS BEGINNING ==================================
  shell: echo

# MANDATORY SO PERHAPS THIS BELONGS IN 3-BASE-SERVER ?
- block:
    - name: SSHD
      shell: echo
    - import_role:
        name: sshd
  # has no "when: XXXXX_install" flag
  tags: base, sshd

- block:
    - name: OPENVPN
      shell: echo
    - import_role:
        name: openvpn
  when: openvpn_install
  tags: openvpn

#- name: Configuring wondershaper
#  include_tasks: roles/network/tasks/wondershaper.yml
#  when: wondershaper_install
#  tags: wondershaper, network

- block:
    - name: Installing named
      shell: echo
    - import_tasks: roles/network/tasks/named.yml
  when: named_install
  tags: base, named, network, domain

- block:
    - name: Installing dhcpd
      shell: echo
    - import_tasks: roles/network/tasks/dhcpd.yml
  when: dhcpd_install
  tags: base, dhcpd, network, domain

- block:
    - name: Installing Squid
      shell: echo
    - import_tasks: roles/network/tasks/squid.yml
  when: squid_install
  tags: base, squid, network, domain

#- name: NETWORK
#  include_role:
#    name: network
#  # has no "when: XXXXX_install" flag
#  tags: base, network

# MANDATORY SO PERHAPS THIS BELONGS IN 3-BASE-SERVER ?
- block:
    - name: HOMEPAGE
      shell: echo
    - import_role:
        name: homepage
  # has no "when: XXXXX_install" flag
  tags: base, homepage

- block:
    - name: POSTGRESQL
      shell: echo
    - import_role:
        name: postgresql
  when: postgresql_install
  tags: postgresql, pathagar, moodle

- block:
    - name: AUTHSERVER
      shell: echo
    - import_role:
        name: authserver
  when: authserver_install
  tags: olpc, authserver

- block:
    - name: CUPS
      shell: echo
    - import_role:
        name: cups
  when: cups_install
  tags: cups

- block:
    - name: SAMBA
      shell: echo
    - import_role:
        name: samba
  when: samba_install
  tags: samba

- block:
    - name: USB-LIB
      shell: echo
    - import_role:
        name: usb-lib
  when: usb_lib_install
  tags: usb-lib

# MANDATORY SO PERHAPS THIS BELONGS IN 3-BASE-SERVER ?
- name: Create a Python interface to iiab.env
  template:
    src: roles/1-prep/templates/iiab_env.py.j2
    dest: /etc/iiab/iiab_env.py

# MANDATORY SO PERHAPS THIS BELONGS IN 3-BASE-SERVER ?
- name: Generate the offline documents
  command: /usr/bin/iiab-refresh-wiki-docs
  when: not nodocs

- name: Recording STAGE 4 HAS COMPLETED ==================
  lineinfile:
    dest: /etc/iiab/iiab.env
    regexp: '^STAGE=*'
    line: 'STAGE=4'
    state: present
