# For rpi installs

- name: Set some facts for RPi
  set_fact:
    minetest_server_bin: /library/games/minetest/bin/minetestserver
    minetest_world_dir: /library/games/minetest/worlds/world
    minetest_game_dir: /library/games/minetest/games/minetest_game
# only works if server run as root
    minetest_runas_user: root
    minetest_runas_group: root
  when: is_rpi

# For other installs TBD
