# For non-rpi installs
# Still a work in progress

# COMPARE tasks/calc_vars.yml
- name: Set some facts
  set_fact:
    minetest_server_bin: /usr/lib/minetest/minetestserver
#    minetest_world_dir: /var/games/minetest-server/.minetest/worlds/world/ should be in library
    minetest_mods_dir: /usr/share/games/minetest_game/mods/

# Taken care of near top of tasks/main.yml
#
#- name: Ensure Linux group '{{ minetest_runas_group }}' exists
#  group:
#    name: "{{ minetest_runas_group }}"
#    state: present
#  when: minetest_runas_user != 'root'
#
#- name: Ensure Linux user '{{ minetest_runas_user }}' exists
#  user:
#    name: "{{ minetest_runas_user }}"
#    groups: "{{ minetest_runas_group }}"
#    state: present
#    createhome: no
#    shell: /bin/false
#  when: minetest_runas_user != 'root'

# SEE "Check for minetest world file" in tasks/main.yml
#
#- name: Create dir minetest_world_dir ({{ minetest_world_dir }})
#  file:
#    state: directory
#    path: "{{ minetest_world_dir }}"
#    owner: "{{ minetest_runas_user }}"
#    group: "{{ minetest_runas_group }}"
#    mode: 0755

#- name: Warn if not Raspberry Pi
#  debug:
#    msg: "No install except Raspberry Pi for now."
#  when: not is_rpi

- name: Download Minetest if not package
  get_url:
    url: "{{ rpi_src_url }}"
    dest: "{{ downloads_dir }}/{{ rpi_src }}"
    timeout: "{{ download_timeout }}"
  #when: is_rpi

- name: Install Minetest if not package
  debug:
    msg: "placeholder."
  #when: is_rpi

- name: Create /etc/minetest
  file:
    state: directory
    path: /etc/minetest
    owner: root
    group: root
    mode: 0755

# - name: move files to world dir

- name: 'Change minetest_server_bin: /usr/bin/minetest-server if not RPi'
  set_fact:
    minetest_server_bin: /usr/bin/minetest-server
  #when: not is_rpi

- name: Create minetest-server service and minetest.conf file
  template:
    backup: no
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'minetest.conf.j2', dest: '/etc/minetest/minetest.conf' }
    - { src: 'minetest-serve.service.j2', dest: '/etc/systemd/system/minetest-serve.service' }

# - name: Start minetest
