# For rpi installs

- name: Set some facts
  set_fact:
    rpi_src_url: http://www.nathansalapat.com/downloads/0.4.17.1.tar.gz
    rpi_src: minetest-0.4.17.1.tar.gz

- name: Install 'libhiredis-dev' package for Minetest
  package:
    name: libhiredis-dev
    state: present

#- name: Minetest already installed - terminate play
#  meta: end_play
#  when: minetest_world.stat.exists

- name: Download Minetest {{ rpi_src_url }} for RPi
  get_url:
    url: "{{ rpi_src_url }}"
    dest: "{{ downloads_dir }}/{{ rpi_src }}"
    timeout: "{{ download_timeout }}"

- name: Create dirs /etc/minetest and /library/games
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/minetest
    - /library/games

- name: Create dir /var/log/minetest
  file:
    state: directory
    path: /var/log/minetest
    owner: "{{ minetest_runas_user }}"
    group: "{{ minetest_runas_group }}"
    mode: 0755

- name: Extract {{ downloads_dir }}/{{ rpi_src }} into /library/games
  unarchive:
    src: "{{ downloads_dir }}/{{ rpi_src }}"
    dest: /library/games
    owner: "{{ minetest_runas_user }}"
    group: "{{ minetest_runas_group }}"

- name: Create symbolic link /library/games/minetest
  file:
    state: link
    src: /library/games/0.4.17.1
    dest: /library/games/minetest
    owner: "{{ minetest_runas_user }}"
    group: "{{ minetest_runas_group }}"

- name: Create /etc/minetest/minetest.conf and minetest-serve.service
  template:
    backup: no
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'minetest.conf.j2', dest: '/etc/minetest/minetest.conf' }
    - { src: 'minetest-serve.service.j2', dest: '/etc/systemd/system/minetest-serve.service' }
