# Generic Apps

- name: ...IS BEGINNING ====================================
  command: echo

- name: DOKUWIKI
  import_role:
    name: dokuwiki
  when: dokuwiki_install
  tags: dokuwiki

- name: MEDIAWIKI
  import_role:
    name: mediawiki
  when: mediawiki_install
  tags: mediawiki

- name: ELGG
  import_role:
    name: elgg
  when: elgg_install
  tags: elgg

- name: EJABBERD
  import_role:
    name: ejabberd
  when: ejabberd_install
  tags: ejabberd

- name: NEXTCLOUD
  import_role:
    name: nextcloud
  when: nextcloud_install
  tags: nextcloud

- name: OWNCLOUD
  import_role:
    name: owncloud
  when: owncloud_install
  tags: owncloud

- name: WORDPRESS
  import_role:
    name: wordpress
  when: wordpress_install
  tags: wordpress

- name: Recording STAGE 6 HAS COMPLETED ====================
  lineinfile:
    dest: /etc/iiab/iiab.env
    regexp: '^STAGE=*'
    line: 'STAGE=6'
    state: present
