# Generic Apps

- name: ...IS BEGINNING ====================================
  shell: echo

- block:
    - name: DOKUWIKI
      shell: echo
    - import_role:
        name: dokuwiki
  when: dokuwiki_install
  tags: dokuwiki

- block:
    - name: MEDIAWIKI
      shell: echo
    - import_role:
        name: mediawiki
  when: mediawiki_install
  tags: mediawiki

- block:
    - name: ELGG
      shell: echo
    - import_role:
        name: elgg
  when: elgg_install
  tags: elgg

- block:
    - name: EJABBERD
      shell: echo
    - import_role:
        name: ejabberd
  when: ejabberd_install
  tags: ejabberd

- block:
    - name: NEXTCLOUD
      shell: echo
    - import_role:
        name: nextcloud
  when: nextcloud_install
  tags: nextcloud

- block:
    - name: OWNCLOUD
      shell: echo
    - import_role:
        name: owncloud
  when: owncloud_install
  tags: owncloud

- block:
    - name: WORDPRESS
      shell: echo
    - import_role:
        name: wordpress
  when: wordpress_install
  tags: wordpress

- name: Recording STAGE 6 HAS COMPLETED ====================
  lineinfile:
    dest: /etc/iiab/iiab.env
    regexp: '^STAGE=*'
    line: 'STAGE=6'
    state: present
