# Generic Apps

- name: ...IS BEGINNING ====================================
  command: echo

- name: DOKUWIKI
  include_role:
    name: dokuwiki
  when: dokuwiki_install
  tags: dokuwiki

- name: MEDIAWIKI
  include_role:
    name: mediawiki
  when: mediawiki_install
  tags: mediawiki

- name: EJABBERD
  include_role:
    name: ejabberd
  when: ejabberd_install
  tags: ejabberd

- name: ELGG
  include_role:
    name: elgg
  when: elgg_install
  tags: elgg

- name: GITEA
  include_role:
    name: gitea
  when: gitea_install
  tags: gitea

- name: LOKOLE
  include_role:
    name: lokole
  when: lokole_install
  tags: lokole

- name: MOSQUITTO
  include_role:
    name: mosquitto
  when: mosquitto_install
  tags: mosquitto

- name: NODE-RED
  include_role:
    name: nodered
  when: nodered_install
  tags: nodered

- name: NEXTCLOUD
  include_role:
    name: nextcloud
  when: nextcloud_install
  tags: nextcloud

#- name: OWNCLOUD
#  include_role:
#    name: owncloud
#  when: owncloud_install
#  tags: owncloud

- name: PBX
  include_role:
    name: pbx
  when: pbx_install
  tags: pbx  

- name: WORDPRESS
  include_role:
    name: wordpress
  when: wordpress_install
  tags: wordpress

- name: Recording STAGE 6 HAS COMPLETED ====================
  lineinfile:
    dest: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=6'
    state: present
