- name: Install DokuWiki
  include_tasks: install.yml
  when: dokuwiki_install

- name: Add 'dokuwiki' variable values to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"
    section: dokuwiki
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: name
      value: DokuWiki
    - option: description
      value: '"DokuWiki is a simple to use and highly versatile Open Source wiki software that does not require a database."'
    - option: installed
      value: "{{ dokuwiki_install }}"
    - option: enabled
      value: "{{ dokuwiki_enabled }}"
