- name: Create home directory
  file: path={{ doc_root }}/home
        mode=0755
        owner={{ apache_user }}
        group={{ apache_user }}
        state=directory

- name: Install admin homepage into apache2
  template: src=iiab-homepage.conf
            dest=/etc/{{ apache_config_dir }}/iiab-homepage.conf

- name: Enable the home page
  file: src=/etc/{{ apache_config_dir }}/iiab-homepage.conf
        dest=/etc/apache2/sites-enabled/iiab-homepage.conf
        state=link
  when: is_debuntu
