- name: Create dir {{ doc_root }}/home
  file:
    path: "{{ doc_root }}/home"
    owner: "{{ apache_user }}"
    group: "{{ apache_user }}"
    mode: 0755
    state: directory

- name: Install /etc/{{ apache_config_dir }}/iiab-homepage.conf from template, for http://box redirect to http://box/home/
  template:
    src: iiab-homepage.conf
    dest: "/etc/{{ apache_config_dir }}/iiab-homepage.conf"

- name: Symlink /etc/apache2/sites-enabled/iiab-homepage.conf to /etc/{{ apache_config_dir }}/iiab-homepage.conf (debuntu)
  file:
    src: "/etc/{{ apache_config_dir }}/iiab-homepage.conf"
    path: /etc/apache2/sites-enabled/iiab-homepage.conf
    state: link
  when: is_debuntu
