# Assessment and Monitoring Tools

- name: ...IS BEGINNING ======================================
  shell: echo

- block:
    - name: AWSTATS
      shell: echo
    - import_role:
        name: awstats
  when: awstats_install
  tags: awstats

- block:
    - name: MONIT
      shell: echo
    - import_role:
        name: monit
  when: monit_install
  tags: monit

- block:
    - name: MUNIN
      shell: echo
    - import_role:
        name: munin
  when: munin_install
  tags: munin

- block:
    - name: PHPMYADMIN
      shell: echo
    - import_role:
        name: phpmyadmin
  when: phpmyadmin_install
  tags: phpmyadmin

- block:
    - name: SUGAR-STATS
      shell: echo
    - import_role:
        name: sugar-stats
  when: sugar_stats_install and ansible_distribution != "CentOS"
  tags: olpc, sugar-stats

- block:
    - name: TEAMVIEWER
      shell: echo
    - import_role:
        name: teamviewer
  when: teamviewer_install
  tags: teamviewer

- block:
    - name: VNSTAT
      shell: echo
    - import_role:
        name: vnstat
  when: vnstat_install
  tags: vnstat

- block:
    - name: XOVIS
      shell: echo
    - import_role:
        name: xovis
  when: xovis_install and ansible_distribution != "CentOS"
  tags: xovis

- name: Recording STAGE 8 HAS COMPLETED ======================
  lineinfile:
    dest: /etc/iiab/iiab.env
    regexp: '^STAGE=*'
    line: 'STAGE=8'
    state: present
