- include_tasks: install.yml
  when: awstats_install

- name: Add 'awstats' to list of services at /etc/iiab/iiab.ini
  ini_file:
    dest: "{{ service_filelist }}"
    section: awstats
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: name
      value: AWStats
    - option: description
      value: '"AWStats (originally known as Advanced Web Statistics) is a package written in Perl which generates static or dynamic html summaries based upon web server logs."'
    - option: installed
      value: "{{ awstats_install }}"
    - option: enabled
      value: "{{ awstats_enabled }}"
