- name: Install dnsmasq
  package:
    name: dnsmasq
    state: present

- name: Install /etc/dnsmasq.d/dnsmasq-iiab, allowing systemd-resolved AND dnsmasq to work (#1306)
  template:
    src: roles/network/templates/network/dnsmasq-iiab
    dest: /etc/dnsmasq.d/dnsmasq-iiab

#- name: Stop dnsmasq
#  service:
#    name: dnsmasq
#    state: stopped

#- name: Configure dnsmasq
#  template:
#    src: "{{ item.src }}"
#    dest: "{{ item.dest }}"
#    owner: root
#    group: root
#    mode: "{{ item.mode }}"
#  with_items:
##   - { src: 'network/dnsmasq.service.rh', dest: '/etc/systemd/system/dnsmasq.service', mode: '0644' }
#   - { src: 'roles/network/templates/network/dnsmasq.conf.j2', dest: '/etc/dnsmasq.conf', mode: '644' }

#- name: Start dnsmasq
#  systemd:
#    name: dnsmasq
#    state: restarted
#    enabled: yes
#    daemon_reload: yes
