#TODO: Use vars instead of hardcoded values
- name: Remove FQDN with 172.18.96.1 in /etc/hosts without LAN (if iiab_lan_iface == "none" and not installing)
  lineinfile:
    path: /etc/hosts
    regexp: '^172\.18\.96\.1'
    state: absent
  when: iiab_lan_iface == "none" and not installing

- name: Configure FQDN with 172.18.96.1 in /etc/hosts with LAN (if iiab_lan_iface != "none" and not installing)
  lineinfile:
    path: /etc/hosts
    regexp: '^172\.18\.96\.1'
    line: '172.18.96.1     {{ iiab_hostname }}.{{ iiab_domain }} {{ iiab_hostname }} box box.lan'
    state: present
  when: iiab_lan_iface != "none" and not installing

- name: Configure FQDN with 127.0.0.1 in /etc/hosts appliance mode (if iiab_lan_iface == "none" and not installing)
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1     localhost.localdomain localhost {{ iiab_hostname }}.{{ iiab_domain }} {{ iiab_hostname }} box box.lan'
    owner: root
    group: root
    mode: 0644
  when: iiab_lan_iface == "none" and not installing
