- include_tasks: detected_network.yml
  when: not installing
  tags:
    - network
    - network-discover

- include_tasks: computed_network.yml
  when: not installing
  tags:
    - network
    - network-discover

##### Start static ip address info for first run #####
#- include_tasks: static.yml
#  when: 'iiab_wan_iface != "none" and wan_ip != "dhcp"'
##### End static ip address info

- include_tasks: hosts.yml
  tags:
    - network
    - hostname
    - domain

- include_tasks: named.yml
  tags:
    - named
    - network
    - domain

- include_tasks: dhcpd.yml
  tags:
    - dhcpd
    - network
    - domain

- include_tasks: squid.yml
  tags:
    - squid
    - network
  when: squid_install

- include_tasks: wondershaper.yml
  tags:
    - wondershaper
    - network

- include_tasks: iptables.yml
  tags:
    - iptables
    - network

- include_tasks: avahi.yml
  tags:
    - network

- name: Ask systemd to reread the unit files, picks up changes done
  shell: systemctl daemon-reload
  when: not installing

- include_tasks: ifcfg_mods.yml
  tags:
    - network
  when: is_redhat and not installing

- include_tasks: debian.yml
  tags:
    - network
  when: is_debuntu and not is_rpi  and not installing

- include_tasks: rpi_debian.yml
  tags:
    - network
  when: is_debuntu and is_rpi  and not installing

- name: Create IIAB network flags
  template: src=network/{{ item }}.j2
            dest=/etc/sysconfig/{{ item }}
            mode=0644
  with_items:
    - iiab_wan_device
    - iiab_lan_device
  when: not installing
  tags:
    - network

- include_tasks: computed_services.yml
  tags:
    - network

- include_tasks: enable_services.yml
  tags:
    - network

- include_tasks: restart.yml
  when: not installing
  tags:
    - network

- include_tasks: hostapd.yml
  when: not installing
  tags:
    - network
