#- name: "Install 10 yum/dnf packages: avahi, avahi-tools, createrepo, linux-firmware, nss-mdns, openssl, syslog, wpa_supplicant, xml-common, yum-utils (redhat)"
#  package:
#    name:
#      - avahi
#      - avahi-tools
#      - createrepo
#      - linux-firmware
#      - nss-mdns
#      - openssl    # FC 18 does not supply, but pear requires
#      - syslog
#      - wpa_supplicant
#      - xml-common
#      - yum-utils
#    state: present
#  when: is_redhat

- name: '2021-07-27: SEE ALSO ~3 networking packages EARLIER installed by https://github.com/iiab/iiab/blob/master/roles/1-prep/tasks/raspberry_pi.yml'
  meta: noop

- name: '2021-07-27: SEE ALSO 4-5 networking packages LATER installed by https://github.com/iiab/iiab/blob/master/roles/2-common/tasks/network.yml'
  meta: noop

- name: "Install 20 common packages: acpid, avahi-daemon, bzip2, curl, gawk, htop, i2c-tools, libnss-mdns, logrotate, mlocate, net-tools, pandoc, pastebinit, rsync, sqlite3, tar, unzip, usbutils, wget, wpasupplicant"
  package:
    name:
      - acpid              # Daemon for ACPI (power mgmt) events
      - avahi-daemon       # 2021-07-27: RaspiOS (and package libnss-mnds, below) install this regardless -- holdover from the XO days and used to advertise ssh/admin-console being available via avahi-daemon
      #- avahi-discover    # 2021-07-27: Commented out long ago
      - bzip2              # 2021-04-26: Prob not used, but can't hurt?
      - curl               # Used to install roles/nodejs and roles/nodered
      #- etckeeper         # "nobody is really using etckeeper and it's bloating the filesystem every time apt runs" per @jvonau at https://github.com/iiab/iiab/issues/1146
      #- exfat-fuse        # 2021-07-27: Should no longer be nec with 5.4+ kernels, so let's try commenting it out
      #- exfat-utils       # Ditto!  See also 'ntfs-3g' below
      - gawk
      - htop
      - i2c-tools          # Low-level bus/chip/register/EEPROM tools e.g. for RTC
      #- inetutils-syslogd # 2021-07-27: Error logging facility -- holdover from the XO days, journalctl has replaced this in newer distros
      #- iproute2          # Installed by roles/2-common/tasks/network.yml
      - logrotate
      - libnss-mdns        # 2021-07-27: RaspiOS (and package avahi-daemon, above) install this regardless -- client-side library -- provides name resolution via mDNS (Multicast DNS) using Zeroconf/Bonjour e.g. Avahi
      #- lynx              # Installed by 1-prep's roles/iiab-admin/tasks/access.yml
      #- make              # 2021-07-27: Currently used by roles/pbx and no other roles
      - mlocate
      - net-tools          # 2021-04-26: @jvonau suggests possibly deleting this...unless oldtimers really want these older commands in iiab-diagnostics output?
      #- ntfs-3g           # 2021-07-31: Should no longer be nec with 5.4+ kernels, similar to exfat packages above -- but see this symlink warning: https://superuser.com/questions/1050544/mount-with-kernel-ntfs-and-not-ntfs-3g -- and upcoming kernel 5.15 improvements: https://www.phoronix.com/scan.php?page=news_item&px=New-NTFS-Likely-For-Linux-5.15
      #- openssh-server    # ssh (Raspbian) or openssh-server (other OS's) already installed by 1-prep's roles/sshd/tasks/main.yml
      - pandoc             # For /usr/bin/iiab-refresh-wiki-docs
      - pastebinit         # For /usr/bin/iiab-diagnostics
      - rsync
      #- screen            # Installed by 1-prep's roles/iiab-admin/tasks/access.yml
      - sqlite3
      #- sudo              # Installed by 1-prep's roles/iiab-admin/tasks/sudo-prereqs.yml
      - tar
      - unzip
      #- usbmount          # Moved to roles/usb_lib/tasks/install.yml
      - usbutils           # 2021-07-27: RaspiOS installs this regardless -- move to roles/usb_lib/tasks/install.yml ?
      - wget
      - wpasupplicant      # 2021-07-27: RaspiOS installs this regardless -- client library for connections to a WiFi AP
    state: present
