- name: "Install 10 yum/dnf packages: avahi, avahi-tools, createrepo, linux-firmware, nss-mdns, openssl, syslog, wpa_supplicant, xml-common, yum-utils (redhat)"
  package:
    name:
      - avahi
      - avahi-tools
      - createrepo
      - linux-firmware
      - nss-mdns
      - openssl    # FC 18 does not supply, but pear requires
      - syslog
      - wpa_supplicant
      - xml-common
      - yum-utils
    state: present
  when: is_redhat

- name: "Install 6 deb/apt packages: avahi-daemon, exfat-fuse, exfat-utils, inetutils-syslogd, libnss-mdns, wpasupplicant (debuntu)"
  package:
    name:
      #- avahi-discover
      - avahi-daemon
      - exfat-fuse     # Should no longer be nec with 5.4+ kernels
      - exfat-utils    # Likewise!
      - inetutils-syslogd    # Error logging facility
      - libnss-mdns    # Provides name resolution via mDNS (Multicast DNS) using Zeroconf/Bonjour e.g. Avahi
      - wpasupplicant
    state: present
  when: is_debuntu

- name: "Install 20 common packages: acpid, bridge-utils, bzip2, curl, gawk, hostapd, htop, i2c-tools, logrotate, make, mlocate, netmask, net-tools, ntfs-3g, pandoc, pastebinit, rsync, sqlite3, tar, unzip, usbutils, wget"
  package:
    name:
      - acpid         # Daemon for ACPI (power mgmt) events
      - bzip2         # 2021-04-26: Prob not used, but can't hurt?
      - curl          # Used to install roles/nodejs and roles/nodered
      #- etckeeper    # "nobody is really using etckeeper and it's bloating the filesystem every time apt runs" per @jvonau at https://github.com/iiab/iiab/issues/1146
      - gawk
      - htop
      - i2c-tools     # Low-level bus/chip/register/EEPROM tools e.g. for RTC
      - iproute2
      - logrotate
      #- lynx         # Installed by 1-prep's roles/iiab-admin/tasks/access.yml
      - make          # 2021-04-26: What roles (if any) truly still use this?
      - mlocate
      - net-tools     # 2021-04-26: @jvonau suggests possibly deleting this...unless oldtimers really want these older commands in iiab-diagnostics output?
      - ntfs-3g       # Possibly no longer nec, similar to exfat packages above?
      #- openssh-server    # ssh (Raspbian) or openssh-server (other OS's) already installed by 1-prep's roles/sshd/tasks/main.yml
      - pandoc        # For /usr/bin/iiab-refresh-wiki-docs
      - pastebinit    # For /usr/bin/iiab-diagnostics
      - rsync
      #- screen       # Installed by 1-prep's roles/iiab-admin/tasks/access.yml
      - sqlite3
      #- sudo         # Installed by 1-prep's roles/iiab-admin/tasks/sudo-prereqs.yml
      - tar
      - unzip
      #- usbmount     # Moved to roles/usb_lib/tasks/install.yml
      - usbutils      # 2021-04-26: Also move to roles/usb_lib/tasks/install.yml ?
      - wget
    state: present
