# Might stall MongoDB on Power Failure: github.com/xsce/xsce/issues/879
# Sugarizer 1.0.1+ strategies to solve? github.com/iiab/iiab/pull/957

# sugarizer_install: False
# sugarizer_enabled: False
# sugarizer_port: 8089

# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!

sugarizer_dir_version: sugarizer-1.1.0    # WAS: sugarizer-1.0, sugarizer-master
sugarizer_git_version: v1.1.0             # WAS: v1.0.1, master
# PLEASE HELP MONITOR https://github.com/llaske/sugarizer/releases

sugarizer_server_dir_version: sugarizer-server-dev                        # WAS: sugarizer-server-1.0, sugarizer-server-master
sugarizer_server_git_version: f27bf6acd56aba6d99116ef471ca713b0f0dfed3    # WAS: v1.0.1, master, dev
# Above commit (githash f27bf6a... for iiab/iiab PR #1430 from 'dev' branch of
# https://github.com/llaske/sugarizer-server) well-tested Jan 29 - Feb 12 2019.
#
# PLEASE HELP MONITOR https://github.com/llaske/sugarizer-server/commits/dev
#                 AND https://github.com/llaske/sugarizer-server/releases
