# Local Add-ons

- name: ...IS BEGINNING ====================================
  command: echo

- name: INTERNETARCHIVE
  include_role:
    name: internetarchive
  tags: internetarchive

# Until porting complete (@jvonau helping transition to Python 3)
- name: 'Install Python 2.7 packages: python, python-pip'
  package:
    name:
      - python
      - python-pip    # Used by Admin Console
    state: present

# Used by iiab-update-map, supplied by osm-vector-maps
- name: Create a Python interface to iiab.env
  template:
    src: roles/1-prep/templates/iiab_env.py.j2
    dest: /etc/iiab/iiab_env.py

- name: CAPTIVE PORTAL
  include_tasks: roles/captive-portal/tasks/main.yml
  when: captive_portal_install | bool
  tags: base, captive-portal, network, domain

- name: MINETEST
  include_role:
    name: minetest
  tags: minetest

# KEEP AT THE END as this installs dependencies from Debian's 'testing' branch!
- name: CALIBRE
  include_role:
    name: calibre
  tags: calibre

- name: CALIBRE-WEB
  include_role:
    name: calibre-web
  tags: calibre-web

- name: Recording STAGE 9 HAS COMPLETED ====================
  lineinfile:
    dest: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=9'
    state: present
