# "How do i fail a task in Ansible if the variable contains a boolean value?
# I want to perform input validation for Ansible playbooks"
# https://stackoverflow.com/questions/46664127/how-do-i-fail-a-task-in-ansible-if-the-variable-contains-a-boolean-value-i-want/46667499#46667499

# We assume 0-init/tasks/validate_vars.yml has DEFINITELY been run, so no need
# to re-check whether vars are defined here.  As Ansible vars cannot be unset:
# https://serverfault.com/questions/856729/how-to-destroy-delete-unset-a-variable-value-in-ansible

- name: Assert that "nodered_install is sameas true" (boolean not string etc)
  assert:
    that: nodered_install is sameas true
    fail_msg: "PLEASE SET 'nodered_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "nodered_enabled | type_debug == 'bool'" (boolean not string etc)
  assert:
    that: nodered_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'nodered_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes


- name: Install Node-RED if nodered_installed is not defined, e.g. in {{ iiab_state_file }}    # /etc/iiab/iiab_state.yml
  include_tasks: install.yml
  when: nodered_installed is undefined


- name: Enable & (Re)start 'nodered' systemd service, if nodered_enabled
  systemd:
    name: nodered
    daemon_reload: yes
    enabled: yes
    state: restarted
  when: nodered_enabled

- name: Disable & Stop 'nodered' systemd service, if not nodered_enabled
  systemd:
    name: nodered
    enabled: no
    state: stopped
  when: not nodered_enabled

#- name: Enable/Disable/Restart Apache if primary
- name: SHIM FOR NOW SO ALWAYS DO THE...Enable/Disable/Restart Apache
  include_tasks: apache.yml
  when: not nginx_enabled

- name: Enable/Disable/Restart NGINX if primary
  include_tasks: nginx.yml
  when: nginx_enabled


- name: Add 'nodered' variable values to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"    # /etc/iiab/iiab.ini
    section: nodered
    option: "{{ item.option }}"
    value: "{{ item.value | string }}"
  with_items:
    - option: name
      value: Node-RED
    - option: description
      value: '"Node-RED is a flow-based development tool for visual programming developed originally by IBM for wiring together hardware devices, APIs and online services as part of the Internet of Things.  Node-RED provides a web browser-based flow editor, which can be used to create JavaScript functions."'
    - option: nodered_install
      value: "{{ nodered_install }}"
    - option: nodered_enabled
      value: "{{ nodered_enabled }}"
