# 2019-01-16: @jvonau's PR #1403 moved installation of Node.js (8.x for now) &
# npm to roles/nodejs/tasks/main.yml, triggered by roles/nodered/meta/main.yml

- name: 'npm install node-red packages globally: node-red, node-red-admin, node-red-dashboard'
  shell: npm install -g --unsafe-perm node-red node-red-admin node-red-dashboard
  when: nodered_install

- name: Ensure Linux group 'nodered' exists
  group:
    name: nodered
    state: present
  when: nodered_install

- name: Ensure Linux user 'nodered' exists and is added to group 'nodered'
  user:
    name: nodered
    group: nodered
  when: nodered_install

- name: Create /home/nodered/.node-red/ directory
  file:
    path: /home/nodered/.node-red
    state: directory
    owner: nodered
    group: nodered
    mode: 0775
  when: nodered_install

- name: Install /home/nodered/.node-red/settings.js from template, with authentication
  template:
    backup: yes
    src: settings.js.j2
    dest: /home/nodered/.node-red/settings.js
    owner: nodered
    group: nodered
    mode: 0755
  when: nodered_install

- name: Install /etc/systemd/system/node-red.service systemd unit file from template
  template:
    backup: yes
    src: node-red.service.j2
    dest: /etc/systemd/system/node-red.service
    owner: root
    group: root
    mode: 0666
  when: nodered_install

- name: Install Apache's sites-available/nodered.conf from template
  template:
    backup: yes
    src: nodered.conf.j2
    dest: /etc/apache2/sites-available/nodered.conf
    owner: root
    group: root
    mode: 0666
  when: nodered_install

- name: Create symlink nodered.conf from sites-enabled to sites-available, for short URL http://box/nodered (if nodered_enabled)
  file:
    src: /etc/apache2/sites-available/nodered.conf
    dest: /etc/apache2/sites-enabled/nodered.conf
    owner: root
    group: root
    state: link
  when: nodered_enabled

- name: Remove symlink /etc/apache2/sites-enabled/nodered.conf (if not nodered_enabled)
  file:
    path: /etc/apache2/sites-enabled/nodered.conf
    state: absent
  when: not nodered_enabled

- name: Enable proxy_wstunnel apache2 module
  apache2_module:
    state: present
    name: proxy_wstunnel
  when: nodered_install

- name: Restart Apache service ({{ apache_service }}) to enable/disable http://box/nodered (not just http://box:{{ nodered_port }})
  systemd:
    #daemon_reload: yes
    name: "{{ apache_service }}"    # httpd or apache2
    state: restarted
  when: nodered_install

- name: Enable & (Re)start 'node-red' systemd service (if nodered_enabled)
  systemd:
    daemon_reload: yes
    name: node-red
    enabled: yes
    state: restarted
  when: nodered_enabled

- name: Disable & Stop 'node-red' systemd service (if not nodered_enabled)
  systemd:
    daemon_reload: yes
    name: node-red
    enabled: no
    state: stopped
  when: not nodered_enabled

- name: Add 'nodered' variable values to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"
    section: nodered
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: name
      value: Node-RED
    - option: description
      value: '"Node-RED is a flow-based development tool for visual programming developed originally by IBM for wiring together hardware devices, APIs and online services as part of the Internet of Things. Node-RED provides a web browser-based flow editor, which can be used to create JavaScript functions."'
    - option: nodered_install
      value: "{{ nodered_install }}"
    - option: nodered_enabled
      value: "{{ nodered_enabled }}"
