- name: Set up Node.js 8.x apt sources (debuntu distros up to 2017)
  shell: curl -sL https://deb.nodesource.com/setup_8.x | bash -
  args:
    warn: no
  when: internet_available and (is_debian_8 or is_debian_9 or is_ubuntu_16 or is_ubuntu_17) and nodered_install
  # NOT NEC TO TEST FOR is_raspbian_8 OR is_raspbian_9 AS /opt/iiab/iiab/vars/<OS>.yml
  # DEFINES THESE AS SUBSETS OF is_debian_8 OR is_debian_9 (FOR NOW!)
  
- name: Install latest Node.js which includes /usr/bin/npm (debuntu distros up to 2017)
  package:
    name: nodejs
    # name: nodejs=8.x
    state: latest
    # state: present
  when: internet_available and (is_debian_8 or is_debian_9 or is_ubuntu_16 or is_ubuntu_17) and nodered_install

# 2019-01-15: WE'RE BORROWING npm INSTALLATION TRICKS FROM MID-2018 SUGARIZER:
# https://github.com/iiab/iiab/blob/master/roles/sugarizer/tasks/main.yml#L77-L94

- name: Install latest packages nodejs and npm (debuntu distros after 2017, or other distros)
  package:
    name:
      - nodejs
      - npm
    state: latest
  when: internet_available and not (is_debian_8 or is_debian_9 or is_ubuntu_16 or is_ubuntu_17) and nodered_install


- name: 'npm install node-red packages globally: node-red, node-red-admin, node-red-dashboard'
  shell: npm install -g --unsafe-perm node-red node-red-admin node-red-dashboard
  when: nodered_install

- name: Ensure Linux group "nodered" exists
  group:
    name: nodered
    state: present
  when: nodered_install

- name: Ensure Linux user "nodered" exists and is added to group "nodered"
  user:
    name: nodered
    group: nodered
  when: nodered_install

- name: Create /home/nodered/.node-red/ directory
  file:
    path: /home/nodered/.node-red
    state: directory
    owner: nodered
    group: nodered
    mode: 0775
  when: nodered_install

- name: Install /home/nodered/.node-red/settings.js from template, with authentication
  template:
    backup: yes
    src: settings.js.j2
    dest: /home/nodered/.node-red/settings.js
    owner: nodered
    group: nodered
    mode: 0755
  when: nodered_install

- name: Install /etc/systemd/system/node-red.service systemd unit file from template
  template:
    backup: yes
    src: node-red.service.j2
    dest: /etc/systemd/system/node-red.service
    owner: root
    group: root
    mode: 0666
  when: nodered_install

- name: Enable & Start node-red service
  systemd:
    daemon_reload: yes
    name: node-red
    enabled: yes
    state: started
  when: nodered_enabled
