# Base Server

- name: ...IS BEGINNING =====================================
  shell: echo

- block:
    - name: HTTPD
      shell: echo
    - import_role:
        name: httpd
  # has no "when: XXXXX_install" flag
  tags: base, httpd

- block:
    - name: IIAB-ADMIN
      shell: echo
    - import_role:
        name: iiab-admin
  # has no "when: XXXXX_install" flag
  tags: base, iiab-admin

- block:
    - name: MYSQL
      shell: echo
    - import_role:
        name: mysql
  # has no "when: XXXXX_install" flag
  tags: base, mysql

- name: Restart httpd
  service:
    name: "{{ apache_service }}"
    state: restarted
  when: not installing

- name: Recording STAGE 3 HAS COMPLETED =====================
  lineinfile:
    dest: /etc/iiab/iiab.env
    regexp: '^STAGE=*'
    line: 'STAGE=3'
    state: present
