- name: Copy css files to {{ doc_root }}/common/css    # doc_root is /library/www/html
  copy:
    src: "{{ item }}"
    dest: "{{ doc_root }}/common/css"
    mode: 0644
    owner: root
    group: root
  with_fileglob:
    - html/css/*.css

- name: Copy js files to {{ doc_root }}/common/js    # doc_root is /library/www/html
  copy:
    src: "{{ item }}"
    dest: "{{ doc_root }}/common/js"
    mode: 0644
    owner: root
    group: root
  with_fileglob:
    - html/js/*.js

- name: Copy fonts files to {{ doc_root }}/common/fonts    # doc_root is /library/www/html
  copy:
    src: "{{ item }}"
    dest: "{{ doc_root }}/common/fonts"
    mode: 0644
    owner: root
    group: root
  with_fileglob:
    - html/fonts/*

- name: Copy html files to {{ doc_root }}/common/html    # doc_root is /library/www/html
  copy:
    src: "{{ item }}"
    dest: "{{ doc_root }}/common/html"
    mode: 0644
    owner: root
    group: root
  with_fileglob:
    - html/html/*

- name: Copy assets files to {{ doc_root }}/common/assets    # doc_root is /library/www/html
  copy:
    src: "{{ item }}"
    dest: "{{ doc_root }}/common/assets"
    mode: 0644
    owner: root
    group: root
  with_fileglob:
    - html/assets/*

# copy all services, even if not permissioned elsewhere
- name: Copy services files to {{ doc_root }}/common/services    # doc_root is /library/www/html
  copy:
    src: "{{ item }}"
    dest: "{{ doc_root }}/common/services"
    mode: 0644
    owner: root
    group: root
  with_fileglob:
    - html/services/*

- name: Symlink {{ doc_root }}/common/assets/iiab.ini to {{ iiab_ini_file }}    # doc_root is /library/www/html
  file:
    src: "{{ iiab_ini_file }}"
    path: "{{ doc_root }}/common/assets/iiab.ini"
    owner: root
    group: root
    state: link
