name: 'TEST on Ubuntu 24.04 on x86-64'
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

# https://michaelcurrin.github.io/dev-cheatsheets/cheatsheets/ci-cd/github-actions/triggers.html
on: [push, pull_request, workflow_dispatch]

# on:
#   push:
#
#   pull_request:
#
#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:
#
#   # Set your workflow to run every day of the week from Monday to Friday at 6:00 UTC
#   schedule:
#     - cron: "0 6 * * 1-5"

jobs:
  test-install:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      #- name: Dump GitHub context (typically almost 500 lines)
      #  env:
      #    GITHUB_CONTEXT: ${{ toJSON(github) }}
      #  run: echo "$GITHUB_CONTEXT"
      - name: Check out repository code    # Clones repo onto github runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 10000    # Default is 1, but iiab-summary (below) needs git tag history
      - run: |
          uname -a    # uname -srm
          whoami      # Typically 'runner' instead of 'root'
          pwd         # /home/runner/work/iiab/iiab == $GITHUB_WORKSPACE == ${{ github.workspace }}
          cd /home/runner/work/iiab/iiab
          git status
          git branch -vv
          git log --oneline | wc
          git describe --tags --abbrev=0
          git describe --tags
          git describe
