name: Test SMALL-sized IIAB install

# on: push
# on: [push]
# on: [push, fork]

on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Set your workflow to run every day of the week from Monday to Friday at 2:00 UTC
  # schedule:
  # - cron: "0 2 * * 1-5"

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: /opt/iiab/iiab
      - run: |
          sudo apt update             ####
          # sudo apt dist-upgrade -y
          # sudo apt autoremove -y
          whoami                      ####
          pwd                         ####
          ls -la $GITHUB_WORKSPACE    ####
          ls -la /opt/iiab/iiab       ####
          sudo mkdir /opt/iiab
          sudo mv $GITHUB_WORKSPACE/iiab /opt/iiab
          cd /opt/iiab/iiab
          ls -la                      ####
          sudo mkdir /etc/iiab
          # touch /etc/iiab/local_vars.yml
          sudo vars/local_vars_small.yml /etc/iiab/local_vars.yml
          sudo ./iiab-install
      - name: Another command
        run: ls -l
